apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-python-cronjob
spec:
  schedule: "*/1 * * * *"  
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backend-service-container
            image: jeriljoshy/my-backup:latest
            # volumeMounts:
            # - name: google-credentials-volume
            #   mountPath: /client_secret_912153419985-mulrp66u9s4qrcfshb5nmc80sj4d1vqu.apps.googleusercontent.com.json
            #   readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: my-data-pvc  # Name of the PersistentVolumeClaim
          - name: google-credentials-volume
            secret:
              secretName: google-credentials


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: google-api-secret
# type: Opaque
# data:
#   client_secret.json: /encoded_credentials.txt
